name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC (5:30 AM IST)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Você pode adicionar mais opções aqui para personalizar o que aparece, como:
          # SHOW_TITLE: true
          # SECTION_NAME: waka # O nome da seção no README, se diferente de 'waka'
          # SHOW_COMMIT: true
          # SHOW_DAYS_OF_WEEK: true
          # SHOW_OS: true
          # SHOW_PROJECTS: true
          # SHOW_EDITORS: true
          # SHOW_LANGUAGE_PER_OS: true
          # SHOW_LANGUAGE_PER_PROJECT: true
          # SHOW_TIMEZONE: true
          # COMPACT_LANGUAGE: false
          # LANG_STATS_ROWS: 5 # Número de linguagens a serem mostradas
          # LANG_STATS_COLUMNS: 6
